export const CHANGE_INPUT_VALUE = 'change_input_value'
export const ADD_ITEM = 'add_item'
export const DEL_ITEM = 'del_item'
export const INIT_DATA = 'init_data'
export const INIT_LIST_DATA = 'init_list_data'
